---
  version: '3.5'

  secrets:
    tomcat_ssl_crt:
      file: ./certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./certificates/tomcat/tomcat-wildcard-dev.key
    water_auth_secret:
      file: ./secrets/oauthClientSecret.txt

  services:
    aqcu-ui:
      build: .
      image: aqcu-ui
      ports:
        - "80:80"
        - "443:443"
      secrets:
        - source: tomcat_ssl_crt
          target: /tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /tomcat-wildcard-ssl.key
        - source: water_auth_secret
          target: /oauthClientSecret.txt
      env_file:
        - "compose.env"