CATALINA_OPTS="-server"
export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote=true"
export JAVA_OPTS="$JAVA_OPTS -Djava.security.egd=file:/dev/./urandom"
export JAVA_OPTS="$JAVA_OPTS -DkeystoreSSLKey=$keystoreSSLKey"
export JAVA_OPTS="$JAVA_OPTS -DkeystoreLocation=$keystoreLocation"
export JAVA_OPTS="$JAVA_OPTS -DkeystorePassword=$keystorePassword"
export JAVA_OPTS="$JAVA_OPTS -Daqcu_reports_webservice=$aqcuWebserviceUrl"
export JAVA_OPTS="$JAVA_OPTS -Dhttp_port=$serverHttpPort"
export JAVA_OPTS="$JAVA_OPTS -Dhttps_port=$serverHttpsPort"
export JAVA_OPTS="$JAVA_OPTS -Dcida_auth_service_endpoint=$cidaAuthWebserviceUrl"
export JAVA_OPTS="$JAVA_OPTS -Daquarius_service_endpoint=$aquariusServiceUrl"
export JAVA_OPTS="$JAVA_OPTS -Dnwis_ra_home=$nwisRaInterfaceUrl"
export JAVA_OPTS="$JAVA_OPTS -Dnwis_ra_service_url=$nwisRaServiceUrl"
export JAVA_OPTS="$JAVA_OPTS -Dnwis_help_email=$nwisHelpEmail"